export { evaluateCheck } from './checks.ts';
export type { GapCheck } from './checks.ts';
export { loadRegister, saveRegister } from './register.ts';
export type { Attribute, Probe, SubjectEntry, SubjectEvidence } from './register.ts';
export { runChecks, captureHelpSince, helpSurfaceSince } from './check.ts';
export type { CheckOutcome, HelpSince } from './check.ts';
export { renderReport } from './report.ts';
export { probeId, writeEvidence, readEvidence, evidencePath, evidenceDir, previousEvidenceDir } from './evidence.ts';
export { captureHelp, helpSnapshotPath, writeHelpSnapshot, previousHelpSnapshot } from './help-snapshot.ts';
export { summariseHelp, diffHelp, renderHelpDiff } from './help-diff.ts';
export type { HelpKey, HelpNode, HelpJson, HelpSummary, HelpDiff } from './help-diff.ts';
export { selectInstance, selectorContainer, selectorFailure } from './select.ts';
export { flattenKeys, normaliseName, autoMatch } from './match.ts';
export { enumerateExport, enumerateKind, writeReferences, referenceFileName, attributePaths, findByChain } from './enumerate.ts';
export type { Reference, ReferenceAttribute, ReferenceInstance } from './enumerate.ts';
export { KINDS, groupSlug } from './kinds.ts';
export type { KindRule } from './kinds.ts';
export { draftEntry, fmTypeMismatch } from './draft.ts';
